#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/025a70fc-6ac1-49d8-a4e6-46d881c687fe 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool aC;
  bool fan1;
  bool fan2;
  bool light1;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);
  pinMode(D0, OUTPUT);
  pinMode(D1, OUTPUT);
  pinMode(D2, OUTPUT);
  pinMode(D3, OUTPUT);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}



/*
  Since Light1 is READ_WRITE variable, onLight1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLight1Change()  {
  if (light1) {
    digitalWrite(D0, LOW);
  } else {
    digitalWrite(D0, HIGH);
  }
  // Add your code here to act upon Light1 change
}


/*
  Since Fan1 is READ_WRITE variable, onFan1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onFan1Change()  {
  if (fan1) {
    digitalWrite(D1, LOW);
  } else {
    digitalWrite(D1, HIGH);
  }
  // Add your code here to act upon Fan1 change
}

/*
  Since Fan2 is READ_WRITE variable, onFan2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onFan2Change()  {
  if (fan2) {
    digitalWrite(D2, LOW);
  } else {
    digitalWrite(D2, HIGH);
  }
  // Add your code here to act upon Fan2 change
}

/*
  Since AC is READ_WRITE variable, onACChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onACChange()  {
  if (aC) {
    digitalWrite(D3, LOW);
  } else {
    digitalWrite(D3, HIGH);
  }
  // Add your code here to act upon AC change
}






