// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onACChange();
void onFan1Change();
void onFan2Change();
void onLight1Change();

bool aC;
bool fan1;
bool fan2;
bool light1;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(aC, READWRITE, ON_CHANGE, onACChange);
  ArduinoCloud.addProperty(fan1, READWRITE, ON_CHANGE, onFan1Change);
  ArduinoCloud.addProperty(fan2, READWRITE, ON_CHANGE, onFan2Change);
  ArduinoCloud.addProperty(light1, READWRITE, ON_CHANGE, onLight1Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
